I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 219, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 551, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 551, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 565, in _execute_python_hide
    renpy.load(renpy.session["_reload_slot"])
FileNotFoundError: [Errno 2] No such file or directory: '/home/tevo/.renpy/DesenrolaDigital-1746582942/sync/_reload-1-LT1.save'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 219, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 551, in script
    python hide:
  File "/home/tevo/Documents/Jogo TCC - Desenrola/renpy-8.3.7-sdk/renpy/ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/tevo/Documents/Jogo TCC - Desenrola/renpy-8.3.7-sdk/renpy/python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 551, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 565, in _execute_python_hide
    renpy.load(renpy.session["_reload_slot"])
  File "/home/tevo/Documents/Jogo TCC - Desenrola/renpy-8.3.7-sdk/renpy/loadsave.py", line 832, in load
    log_data, signature = location.load(filename)
  File "/home/tevo/Documents/Jogo TCC - Desenrola/renpy-8.3.7-sdk/renpy/savelocation.py", line 585, in load
    return l.load(slotname) # type: ignore
  File "/home/tevo/Documents/Jogo TCC - Desenrola/renpy-8.3.7-sdk/renpy/savelocation.py", line 334, in load
    with zipfile.ZipFile(filename, "r") as zf:
  File "lib/python3.9/zipfile.py", line 1239, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/home/tevo/.renpy/DesenrolaDigital-1746582942/sync/_reload-1-LT1.save'

Linux-6.14.10-arch1-1-x86_64-with-glibc2.41 x86_64
Ren'Py 8.3.7.25031702
Desenrola 
Thu Jun 26 04:43:46 2025
